export const GET_ALL_POSTS = 'GET_ALL_POSTS'
export const GET_SINGLE_POST = 'GET_SINGLE_POST'
export const GET_POSTS_BY_SEARCH = 'GET_POSTS_BY_SEARCH'
export const CREATE_POST = 'CREATE_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const DELETE_POST = 'DELETE_POST'
export const LIKE_POST = 'LIKE_POST'
export const COMMENT_POST = 'COMMENT_POST'

export const LOGIN = 'LOGIN'
export const REGISTER = 'REGISTER'
export const LOGOUT = 'LOGOUT'

export const START_LOADING = 'START_LOADING'
export const END_LOADING = 'END_LOADING'